# `sheldon` configuration file
# ----------------------------
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins]
#############################################################################
# "defer"
[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ['source']

# templates for use zsh-defer
[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

[plugins.my_pre_load]
inline = 'source $XDG_CONFIG_HOME/zsh/rc/pre_load.zsh'

#############################################################################
# program language load
#############################################################################
[plugins.mise]
inline = 'eval "$(mise activate zsh)"'

#############################################################################
# defered plugins
#############################################################################
[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ['defer']

[plugins.zsh-autosuggestions.hooks]
#pre = "~/.config/zsh/rc/integrations/zsh-autosuggestions_atinit.sh"
post = "source ~/.config/zsh/rc/plugin_settings/zsh-autosuggestions_atload.zsh"

[plugins.fast-syntax-highlighting]
github = 'zdharma/fast-syntax-highlighting'
apply = ['defer']

#############################################################################
# zsh config
#############################################################################
[plugins.my_conf_pre_load]
local="~/.config/zsh/rc"
use=["{pre_load,options}.zsh"]

[plugins.my_conf_defered]
local="~/.config/zsh/rc"
use=["{aliases,completion,post_load}.zsh"]
apply = ['defer']

# Original executables
[plugins.my_executables]
local = "~/.config/zsh/bin"
apply = ['path']

# Completion fpath
[plugins.my_fpaths]
local="~/.config/zsh/.zfunc"
apply = ["fpath"]

[plugins.my_plugins]
local="~/.config/zsh/rc"
use=["{functions/*,my_plugins/*}.zsh"]
apply = ['defer']

#############################################################################
# software integrations
#############################################################################
[plugins.software_integrations]
local="~/.config/zsh/rc/integrations"
apply = ['defer']

[plugins.starship]
inline = 'eval "$(starship init zsh)"'

