# `sheldon` configuration file
# ----------------------------
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"
apply = ["defer"]

# templates for use zsh-defer
[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

[plugins]
#############################################################################
# "defer"
#############################################################################
[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ['source']

#############################################################################
# Zshell opt-in
#############################################################################
[plugins.compinit]
inline = 'autoload -Uz compinit && zsh-defer compinit'
[plugins.colors]
inline = 'autoload -Uz colors && zsh-defer colors'

#############################################################################
# program language load
#############################################################################
[plugins.mise]
inline = 'eval "$(mise activate zsh)"'

#############################################################################
# defered plugins
#############################################################################
[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ['defer']

[plugins.zsh-autosuggestions.hooks]
post = "source ~/.config/zsh/rc/integrations/zsh-autosuggestions_atload.zsh"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ['defer']

[plugins.zsh-completions.hooks]
pre = "source ~/.config/zsh/rc/integrations/zsh-autocompletions_atinit.zsh"

[plugins.zsh-syntax-highlighting]
github = 'zsh-users/zsh-syntax-highlighting'
apply = ['defer']

[plugins.fast-syntax-highlighting]
github = "auscompgeek/fast-syntax-highlighting"
apply = ['defer']

#############################################################################
# graphic and view
#############################################################################
[plugins.starship]
inline = 'eval "$(starship init zsh)"'

#############################################################################
# tmux
#############################################################################
[plugins.tmux-xpanes]
github = "greymd/tmux-xpanes"
apply = ['defer']

#############################################################################
# Zsh local config
#############################################################################
[plugins.my_conf_pre_load]
local="~/.config/zsh/rc"
use=["{options}.zsh"]

[plugins.my_conf_defered]
local="~/.config/zsh/rc"
use=["{aliases,completion}.zsh"]
apply = ['defer']

# Original executables
[plugins.my_executables]
local = "~/.config/zsh/bin"
apply = ['path']

# Completion fpath
[plugins.my_fpaths]
local="~/.config/zsh/.zfunc"
apply = ["fpath"]

[plugins.my_plugins]
local="~/.config/zsh/rc"
use=["{functions/*,my_plugins/*}.zsh"]
apply = ['defer']

# Config of cli tools
[plugins.software_integrations]
local="~/.config/zsh/rc/integrations"
apply = ['defer']
