# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins]

# prerequire
[plugins.zsh-defer]
github = "romkatv/zsh-defer"
#apply = ['source']

[plugins.compinit]
inline = 'autoload -Uz compinit && zsh-defer compinit'

# templates for use zsh-defer
[templates]
defer = """
{% for file in files %}
zsh-defer source "{{ file }}"
{% endfor %}
"""

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.autojump]
github = "wting/autojump"
dir = "bin"
apply = ["PATH", "defer"]

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
dir = "src"
apply = ["fpath"]

[plugins.git-open]
github = "paulirish/git-open"
apply = ["defer"]

[plugins.prompt]
github = "sorin-ionescu/prezto"
use = ["modules/prompt"]
apply = ["defer"]

[plugins.powerlevel10k]
#use immediately
github = "romkatv/powerlevel10k"

[plugins.my_conf_defers]
local="~/.config/zsh/features"
use=["{defer/*}.zsh"]
apply = ["defer"]

[plugins.my_conf_source]
local="~/.config/zsh/features"
use=["{!defer/,*}.zsh"]

[plugins.my_commands]
local="~/.config/zsh/commands"
apply = ["defer"]

[plugins.my_themes]
local="~/.config/zsh/theme"

#[plugins.manjaro]
#local = '/usr/share/zsh/'
#use = ["manjaro-zsh-prompt"]
  # Source manjaro-zsh-configuration
  #if [[ -e /usr/share/zsh/manjaro-zsh-config ]]; then
  #  source /usr/share/zsh/manjaro-zsh-config
  #fi
  #if [[ -e /usr/share/zsh/manjaro-zsh-prompt ]]; then
  #  source /usr/share/zsh/manjaro-zsh-prompt
  #fi

