# Helpers are user-defined functions that can be executed inside templates.
# This section is optional.
[helpers]
#color_hex2rgb = "dotter_settings/helpers/color_hex2rgb.rhai"

# A package contains two sections - "files" and "variables".
# Both of those sections are optional - you can have only one if you want.

# The 'files' section is a mapping between the path of the file relative to
# the repository root and its location in the filesystem (where the program
# expects it)
# In this case, say your repository is at `~/.dotfiles`, it will map
# `~/.dotfiles/zsh/zprofile` to `~/.zprofile`,
# and `~/.dotfiles/zshrc` to `~/.zshrc`
# To clarify, folders in the repository don't have to correspond to packages.
# On Windows, '~' is expanded to 'C:\Users\<USERNAME>\'
[shell.files]
# Optional local variables: email+git_username
git = "~/.config/git/gitconfig"
bat = "~/.config/bat/config"

[shell.variables]
# Local variables: install, uninstall, update, autoremove, user_color
install = "echo not defined"
uninstall = "echo not defined"
update = "echo not defined"
autoremove = "echo not defined"
user_color = "7"

[zsh]
depends = ["shell"]

[zsh.files]
"zsh/zprofile" = "~/.config/.zsh/zprofile"
"zshrc" = "~/.config/.zsh/zshrc"

# The 'variables' section contains constants that the templated files
# can access. This section can contain all the types that toml supports,
# and is used by the Handlebars templating engine as the rendering context.
[zsh.variables]
prompt_color = "#00FF00"

[cargo.files]
cargo = "~/.cargo/config"

# A variables-only package, maybe it contains variables that are also
# used by my terminal so I want them to exist when I select either of
# the packages, without having to repeat them.
[graphics.variables]
font_size = 14
primary_color = "#CCCCCC"
background_color = "#333333"

[default]
depends = []

[default.files]

[default.variables]
