---
- name: Init environments
  hosts: localhost
  become: yes
  connection: local
  roles:
    - common
  gather_facts: true
  vars:
    users:
      root: root
      local: "{{ lookup('ansible.builtin.env', 'USER') }}"
  vars_prompt:
    - name: github_name
      prompt: "Input github_name for chezmoi"
      private: no
      default: "kkiyama117"
      
    - name: github_email
      prompt: "Input github_name for chezmoi"
      private: no
      default: "k.kiyama117@gmail.com"
      
