---
- name: Init environments
  hosts: localhost
  become: yes
  connection: local
  roles:
    - common
  gather_facts: true
  vars:
    users:
      root: root
  vars_prompt:
  - name: users_local
    prompt: Please enter user name
    private: no
