---
- name: Init environments
  hosts: localhost
  become: yes
  connection: local
  roles:
    - common
  gather_facts: true
# become_user: "{{ lookup('env', 'USER') }}"


# vars_prompt:
#   - name: "username"
#     prompt: "Enter name"
#     private: no
