---
template:
  direction: Horizontal
  parts:
    - direction: Vertical
      split_size:
        Fixed: 1
      run:
        plugin:
          location: "zellij:tab-bar"
      borderless: true
    - direction: Vertical
      body: true
    - direction: Vertical
      split_size:
        Fixed: 2
      run:
        plugin:
          location: "zellij:status-bar"
      borderless: true

tabs:
- direction: Vertical
  name: "TOP"
  focus: true
  parts:
  - direction: Vertical
    split_size:
      Percent: 50
    focus: true
  - direction: Horizontal
    split_size:
      Percent: 50
    parts:
      - direction: Vertical
        split_size:
          Percent: 50
        run:
          command: {cmd: top}
      - direction: Vertical
        split_size:
          Percent: 50
- direction: Vertical
  name: "Vim"
  borderless: true
