- name: add several items
  environment:
    PATH: "{{ ansible_env.HOME }}/.cargo/bin:{{ ansible_env.PATH }}"
  community.general.cargo:
    name: "{{ item }}"
  loop:
    #- cargo-edit
    #- cargo-expand
    #- cargo-generate
    - cargo-outdated
    - cargo-script
    - cargo-update
    #- cargo-watch
    #- cargo-zigbuild
    #- bootimage
    #- evcxr_repl
    - git-delta
    #- mdbook
    - navi
    - paru
    #- pastel
    - pueue
    - sheldon
    - skim
    #- t-rec
    #- wasm-pack
    - zellij
    #- zoxide
