- name: check cargo_home 
  register: rust_env
  assert:
    that: cargo_home | length != 0
  vars:
    cargo_home:  "{{ lookup('env','CARGO_HOME') }}"
  ignore_errors: yes

- name: set cargo_home path
  when: rust_env is failed
  set_fact:
    cargo_home:  "{{ lookup('env','HOME') }}/.cargo"

- name: add several items
  environment:
    PATH: "{{ cargo_home }}/bin:{{ ansible_env.PATH }}"
  community.general.cargo:
    name: "{{ item }}"
  loop:
    #- cargo-edit
    #- cargo-expand
    #- cargo-generate
    - cargo-outdated
    - cargo-script
    - cargo-update
    #- cargo-watch
    #- cargo-zigbuild
    #- bootimage
    #- evcxr_repl
    - git-delta
    #- mdbook
    - navi
    - paru
    #- pastel
    - pueue
    - sheldon
    - skim
    #- t-rec
    #- wasm-pack
    - zellij
    #- zoxide
