- name: check if gpg key exist
  shell: gpg --list-secret-keys --keyid-format=long
  register: gpg_key_exists
  ignore_errors: yes

# - name: use old key if exists
#   register: use_exists_key
#   when: gpg_key_exists.stdout | length != 0
#   shell: gpg --armor --export

- name: create new key
  when: not (gpg_key_exists.stdout | length != 0)
  register: use_new_key
  shell: gpg --quick-generate-key "{{ github_name }} <{{ github_email }}>" ed25519 default 0
