- name: pacman
  import_tasks: pacman.yml
  become: yes
  become_user: "{{ users.root }}"

- name: rust
  import_tasks: rust.yml
  become: yes
  become_user: "{{ users.local }}"

- name: chezmoi
  import_tasks: chezmoi.yml
  become: yes
  become_user: "{{ users.root }}"

