- name: full system upgrade
  pacman:
    update_cache: yes
    upgrade: yes

- name: add several aur
  pacman:
    name: "{{ item }}"
    state: present
  loop:
     - base-devel
     - chezmoi
     - pkg-config
     - xsel
     - make
     - zsh
