- name: full system upgrade
  paru:
    update_cache: yes
    upgrade: yes

- name: add several aur
  paru:
    name: "{{ item }}"
    state: latest
  loop:
    # rust tools
    - bat
    - deno
    - fd
    - ripgrep
    - tokei
    - topgrade
    - lsd
    - wezterm
    #- volta
    #- hyperfine
    - "google-chrome"
    - "neovim-git"
