- name: check if cargo is installed
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: yes

- name: rust installer
  when: cargo_exists is failed
  block:
  - name: Fetch rustup
    register: rustup_installer
    uri:
      url: https://sh.rustup.rs
      return_content: yes
    tags:
        - rust
  
  - name: Run rustup installer
    when: rustup_installer is success
    register: install_rust
    ansible.builtin.shell:
      cmd: sh -s -- -y
      stdin: "{{ rustup_installer.content }}"
    tags:
      - rust

  - name: print result of install
    ansible.builtin.debug:
      var: install_rust

  - name: check cargo_home 
    register: rust_env
    assert:
      that: cargo_home | length != 0
    vars:
      cargo_home:  "{{ lookup('env','CARGO_HOME') }}"
    ignore_errors: yes
  
  - name: set cargo_home if cargo_home is not set temporary
    when: rust_env is failed
    register: set_cargo_home
    vars:
      cargo_home:  "{{ lookup('env','HOME') }}/.cargo"
    ansible.builtin.copy:
      content: "export PATH={{cargo_home}}/bin:$PATH"
      dest: "{{ lookup('env','HOME') }}/.bash_profile"
  
  - name: Source the bashrc file
    when: set_cargo_home is success
    shell: source /root/.bashrc

